name: Docker Build

on:
  push:
    branches:
      - "master"

jobs:
  docker-build-publish:
    name: Build and publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image to GH Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          tags: node:18.5.0,node:18.5.0-bullseye
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
