name: Docker Build

on:
  push:
    branches:
      - "master"

env:
  TEST_TAG: ghcr.io/curtislarson/node:test
  VERS_TAG: ghcr.io/curtislarson/node:18.5.0
  PLATFORMS: linux/amd64,linux.arm64

jobs:
  docker-build-publish-bullseye:
    name: Build and publish Bullseye
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx (bullseye)
        uses: docker/setup-buildx-action@v2

      - name: Build and Export to Docker
        uses: docker/build-push-action@v3
        with:
          context: ./bullseye
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test Image
        run: |
          docker run --rm ${{ env.TEST_TAG }} --eval 'console.log("hello!")'

      # This is supposed to be cached
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./bullseye
          platforms: ${{ env.PLATFORMS }}
          tags: |
            ${{ env.VERS_TAG }}
            ${{ env.VERS_TAG }}-bullseye
          push: true

  docker-build-publish-bullseye-slim:
    name: Build and publish bullseye-slim
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx (bullseye-slim)
        uses: docker/setup-buildx-action@v2

      - name: Build and Export to Docker
        uses: docker/build-push-action@v3
        with:
          context: ./bullseye-slim
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test Image
        run: |
          docker run --rm ${{ env.TEST_TAG }} --eval 'console.log("hello!")'

      # This is supposed to be cached
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./bullseye-slim
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ env.VERS_TAG }}
            ${{ env.VERS_TAG }}-bullseye-slim
